# Use the official PHP 8.1 image as a base
FROM php:8.1-fpm

# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    apt-transport-https \
    libxml2-dev \
    unixodbc-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libjpeg-dev \
    zlib1g-dev \
    libicu-dev \
    poppler-utils \
    g++ \
    git \
    libaio-dev \
    libmemcached-dev \
    freetds-dev \
    libssl-dev \
    openssl \
    unzip \
    unzip \
    libzip-dev \
    cron \
    curl \
    supervisor

# Install MS SQL Server extensions
RUN wget -qO - https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && wget -qO /etc/apt/sources.list.d/mssql-release.list https://packages.microsoft.com/config/debian/10/prod.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install --no-install-recommends -y msodbcsql17 mssql-tools \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN pecl install sqlsrv pdo_sqlsrv \
    && docker-php-ext-enable sqlsrv pdo_sqlsrv

# Install other PHP extensions
RUN docker-php-ext-install \
    iconv \
    sockets \
    pdo \
    pdo_mysql \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg

RUN docker-php-ext-install exif pcntl bcmath gd zip soap

# Copy custom php.ini file
COPY config/php.ini /usr/local/etc/php/php.ini

# Get the latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN pecl install apcu

RUN docker-php-ext-enable apcu

# Clean up unnecessary files
RUN apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy crontab file to the cron.d directory
COPY /cron/crontab_cont /etc/cron.d/crontab

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/crontab

# Apply cron job
RUN crontab /etc/cron.d/crontab