FROM php:8.1-fpm

# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libjpeg-dev \
    libonig-dev \
    libxml2-dev \
    openssl \
    pkg-config \
    libssl-dev \
    zip \
    unzip \
    libzip-dev \
    iputils-ping \
    libfreetype6-dev \
    poppler-utils \
    cron \
    vim \
    ghostscript \
    dconf-gsettings-backend \
    dconf-cli \
    libgconf-2-4 \
    libreoffice \
    tesseract-ocr \ 
    tesseract-ocr-eng \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Create cache directories and adjust permissions
RUN mkdir -p /var/www/.config /var/www/.cache/dconf \
    && chown -R www-data:www-data /var/www/.config /var/www/.cache/dconf

# Install PHP extensions
RUN docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Copy custom php.ini file
COPY config/php.ini /usr/local/etc/php/php.ini
