FROM php:7.4-fpm

# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libjpeg-dev \
    libonig-dev \
    libxml2-dev \
    openssl \
    pkg-config \
    libssl-dev \
    zip \
    unzip \
    libzip-dev \
    libzip-dev \
    iputils-ping \
    libfreetype6-dev \
    poppler-utils \
    cron \
    default-mysql-client \
    curl


# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip mysqli

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Copia el archivo php.ini personalizado
COPY config/php.ini /usr/local/etc/php/php.ini

RUN pecl install apcu

RUN docker-php-ext-enable apcu mysqli

# Copy crontab file to the cron.d directory
COPY /cron/crontab_ws /etc/cron.d/crontab

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/crontab

# Apply cron job
RUN crontab /etc/cron.d/crontab